AllCops:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - '**/routes/**/*'

Metrics/AbcSize:
  # Make it large for now
  Max: 40
Metrics/ClassLength:
  Exclude:
    - '**/application.rb'
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  # Make it large for now
  Max: 20

Style/Alias:
  EnforcedStyle: prefer_alias_method
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/BlockDelimiters:
  EnforcedStyle: semantic
  IgnoredMethods:
    - lambda
    - proc
    - it
    - Form
    - Schema
Style/ClassAndModuleChildren:
  Exclude:
    - '**/routes/**/*'
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Naming/MethodName:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RegexpLiteral:
  EnforcedStyle: mixed
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/SpecialGlobalVars:
  Enabled: false
Style/StabbyLambdaParentheses:
  EnforcedStyle: require_no_parentheses
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolProc:
  Exclude:
    - '**/routes/**/*'
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInLiteral:
  Enabled: false
